# Docker compose version
version: '3'

services:

  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    #outgoing port:container port
    ports:
      - 8081:8081
    depends_on:
      - mongo

  spring-boot-app:
    build: .
    container_name: java-app
    ports:
      - 8080:8080
    depends_on:
      - mongo