# Docker compose version
version: '3'

services:

  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo

  spring-boot-app:
    image: my-db
    container_name: java-app
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: mongo
      DB_PORT: 27017
      DB_NAME: db_prod
    depends_on:
      - mongo