# Docker compose version
version: '3'

services:

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - /data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: patrik
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: my-solo-project

  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    #outgoing port:container port
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: patrik
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234

  my-solo-project:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongo