name: Tests CI

on:
  workflow_dispatch:
  push:

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: action/checkout@v2

      - name: Set up JDK 11
        uses: action/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build Jar
        run: mvn test